### ISSUE TITLE
Release v1.2.0 to support Django 4.0

### ISSUE THREAD

**Issue by Photonios** [PokaInc/django-admin-hstore-widget#23]
https://github.com/PokaInc/django-admin-hstore-widget/pull/22

Added support for Django 4.x but no new version was released to PyPi.

**Comment by alexandredufour** [comment]
Hello Photonios.
Thanks for the interest you have in this project.
As you can probably guess, this project is not really maintained on a daily basis 😅 .

I'll release this version during the week.
Have a good day.

**Comment by alexandredufour** [comment]
Done !
