### ISSUE TITLE
Support Updated jQuery version

### ISSUE THREAD

**Issue by baseplate-admin** [PokaInc/django-admin-hstore-widget#24]
Hi there, 
Thanks for creating this awesome library. It really solves a good use case.

It seems that django updated their jquery to version 3.6.3.

jQuery deprecated their `.load` call back in 2015 at version 1.8.

All this change requires modifying this line of code 
https://github.com/PokaInc/django-admin-hstore-widget/blob/b1d9a172513b0ea0c39eb7620f96634fac55b5b5/django_admin_hstore_widget/static/admin/js/django_admin_hstore_widget/django_admin_hstore_widget.js#L171

#25  is my initial attempt to fix this :D 

Regards.

**Comment by alexandredufour** [comment]
I've just merged your PR.
Thanks again
PS: A new release will be available soon on pypi

**Comment by baseplate-admin** [comment]
Thanks for fast reply. Thanks again for the awesome work on this project. 

I have a question.  Would you guys be willing to update underscore.js to latest?

**Comment by baseplate-admin** [comment]
I also have Some minor improvement ideas. Would you like some more PR regarding that?
